services:
  fcp-defra-id-example:
    build:
      context: .
      target: production
    image: fcp-defra-id-example
    container_name: fcp-defra-id-example
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-defra-id-example-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
