# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-defra-id-example:
    build:
      target: development
    image: fcp-defra-id-example-development
    container_name: fcp-defra-id-example-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-defra-id-example

networks:
  fcp-defra-id-example:
    name: fcp-defra-id-example
    driver: bridge
