services:
  fcp-defra-id-example:
    build:
      context: .
      target: production
    image: fcp-defra-id-example
    container_name: fcp-defra-id-example
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-defra-id-example-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      DEFRA_ID_ENABLED: ${DEFRA_ID_ENABLED:-false}
      DEFRA_ID_SIGN_OUT_ENABLED: ${DEFRA_ID_SIGN_OUT_ENABLED:-false}
      DEFRA_ID_WELL_KNOWN_URL: ${DEFRA_ID_WELL_KNOWN_URL}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY}
      DEFRA_ID_REDIRECT_URL: http://localhost:3000/auth/sign-in-oidc
      DEFRA_ID_SIGN_OUT_REDIRECT_URL: http://localhost:3000/auth/sign-out-oidc
      REDIS_HOST: redis
      COOKIE_PASSWORD: this-is-a-secret-that-must-be-at-least-32-characters

  redis:
    image: redis
