# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-defra-id-example:
    build:
      target: development
    image: fcp-defra-id-example-development
    container_name: fcp-defra-id-example-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - fcp-defra-id-example

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1
    networks:
      - fcp-defra-id-example

networks:
  fcp-defra-id-example:
    name: fcp-defra-id-example
    driver: bridge

volumes:
  redis_data:
